repos:
 - repo: local
   hooks:
    - id: run-evals
      name: Run evals
      entry: bash -lc 'set -a; [ -f ai/langchain/.env ] && source .env; set +a; cd ai && pipenv run python langchain/tests/integration_tests/test_graph.py'
      language: system
      files: ^ai/langchain/src/agent/.*$
      pass_filenames: false