name: Run LangSmith Eval

on:
  push:
    paths:
      - 'ai/langchain/**'
  workflow_dispatch:
    inputs:
      dataset:
        description: "LangSmith dataset name or ID"
        required: true
        type: string
      experiment_prefix:
        description: "Experiment prefix for this run"
        required: true
        type: string
        default: manual

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the LangGraph agent package with eval extras from manifests
          pip install -e ai/langchain[eval]

      - name: Run evaluator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          LANGSMITH_TRACING: true
          HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
          EVAL_DATASET: ${{ inputs.dataset || 'test-dataset' }}
          EVAL_EXPERIMENT_PREFIX: ${{ inputs.experiment_prefix || format('push-{0}', github.sha) }}
        run: |
          python -c "import sys, os; sys.path.insert(0, 'ai/langchain/tests/integration_tests'); from eval_runner import main; sys.exit(main(['eval', os.environ['EVAL_DATASET'], os.environ['EVAL_EXPERIMENT_PREFIX']]))"


